all:
	mkdir output
	java -jar /home/millas/ParalelME/compiler-master/src/parallelme-compiler/target/parallelme-compiler-0.1-SNAPSHOT-jar-with-dependencies.jar -f Testes.java -o ./output

clear:
	rm -rf output